version: '3'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-monitoring
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 127.0.0.1:3100:3100
    volumes:
      - ./loki/config:/etc/loki
      - ${VOLUME_DIR}/loki/index:/data/loki/index
      - ${VOLUME_DIR}/loki/chunks:/data/loki/chunks
      - ${VOLUME_DIR}/loki/wal:/wal
    command: -config.file=/etc/loki/local-config.yaml
    user: "${UID}:${GID}"
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/config:/etc/promtail
      - ${VOLUME_DIR}/promtail/data:/data
      - ${VOLUME_DIR}/promtail/log:/var/log
    command: -config.file=/etc/promtail/promtail-local-config.yaml
    user: "${UID}:${GID}"
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    user: "${UID}:${GID}"
    restart: unless-stopped
    # ports:
    #   - 9091:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - ${VOLUME_DIR}/prometheus/data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    depends_on:
      - node-exporter
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
  
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: unless-stopped
    # ports:
    #   - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # ports:
    #   - 3333:3000
    volumes:
      - ${VOLUME_DIR}/grafana/data:/var/lib/grafana
      # - ./grafana/config:/etc/grafana
      # - ./grafana/lib:/var/lib/grafana
      # - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    user: "${UID}:${GID}"
    environment:
      # - GF_INSTALL_PLUGINS=grafana-loki-datasource
      - GF_SERVER_ROOT_URL=https://monitor.markklass.dev
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    restart: unless-stopped
    depends_on:
      - loki
